"""update TestCase column2

Revision ID: 8a14b24466ca
Revises: 2edbc786a2a2
Create Date: 2017-11-20 01:37:00.730563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a14b24466ca'
down_revision = '2edbc786a2a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
