"""update TestCase column3

Revision ID: c77611a10623
Revises: 8a14b24466ca
Create Date: 2017-11-20 01:41:06.006657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77611a10623'
down_revision = '8a14b24466ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
