"""update TestCase column6

Revision ID: f1efd070d878
Revises: 622c3af67142
Create Date: 2017-11-20 10:18:39.513326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1efd070d878'
down_revision = '622c3af67142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('hash_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case', 'hash_id')
    # ### end Alembic commands ###
